---
title: "CodeBook"
author: "Elias"
date: "9/15/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Full Data Codes
subject
:	Subject
:		ID from 1 - 30

activity
:	Activity
:	  1 of 6 different Activities:
:    LAYING            SITTING           STANDING            WALKING WALKING_DOWNSTAIRS   WALKING_UPSTAIRS 
:    1944               1777               1906               1722               1406               1544 

time_body_acc_mean_x
:	Time Body Acc Mean X - (original variable name: tBodyAcc-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	0.262624795,	0.27717388,	0.274347260646063,	0.288354225,	1

time_body_acc_mean_y
:	Time Body Acc Mean Y - (original variable name: tBodyAcc-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.024902479,	-0.017161624,	-0.0177434918458972,	-0.01062456,	1

time_body_acc_mean_z
:	Time Body Acc Mean Z - (original variable name: tBodyAcc-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.12101888,	-0.10859642,	-0.108925032737064,	-0.0975893465,	1

time_body_acc_stdev_x
:	Time Body Acc Stdev X - (original variable name: tBodyAcc-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.99236049,	-0.94303003,	-0.607783818968688,	-0.25029286,	1

time_body_acc_stdev_y
:	Time Body Acc Stdev Y - (original variable name: tBodyAcc-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.97699023,	-0.83503193,	-0.510191378479501,	-0.0573355655,	1

time_body_acc_stdev_z
:	Time Body Acc Stdev Z - (original variable name: tBodyAcc-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.97913693,	-0.85077295,	-0.61306429934125,	-0.27873736,	1

time_gravity_acc_mean_x
:	Time Gravity Acc Mean X - (original variable name: tGravityAcc-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	0.81173988,	0.92179307,	0.669226222373046,	0.954666705,	1

time_gravity_acc_mean_y
:	Time Gravity Acc Mean Y - (original variable name: tGravityAcc-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.242943265,	-0.14355124,	0.00403879092060517,	0.118904575,	1

time_gravity_acc_mean_z
:	Time Gravity Acc Mean Z - (original variable name: tGravityAcc-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.116714505,	0.03680105,	0.0921508600211059,	0.216205875,	1

time_gravity_acc_stdev_x
:	Time Gravity Acc Stdev X - (original variable name: tGravityAcc-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.994945455,	-0.98185253,	-0.965207115039421,	-0.961534505,	1

time_gravity_acc_stdev_y
:	Time Gravity Acc Stdev Y - (original variable name: tGravityAcc-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.99129917,	-0.97587663,	-0.95440802665318,	-0.94642926,	1

time_gravity_acc_stdev_z
:	Time Gravity Acc Stdev Z - (original variable name: tGravityAcc-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.986581485,	-0.96654446,	-0.938900969424022,	-0.929570375,	1

time_body_acc_jerk_mean_x
:	Time Body Acc Jerk Mean X - (original variable name: tBodyAccJerk-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	0.0629804815,	0.075974845,	0.0789381220355816,	0.091309116,	1

time_body_acc_jerk_mean_y
:	Time Body Acc Jerk Mean Y - (original variable name: tBodyAccJerk-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.018554996,	0.010752703,	0.0079481069090025,	0.0335382865,	1

time_body_acc_jerk_mean_z
:	Time Body Acc Jerk Mean Z - (original variable name: tBodyAccJerk-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.0315523735,	-0.0011592989,	-0.00467469823628666,	0.024577969,	1

time_body_acc_jerk_stdev_x
:	Time Body Acc Jerk Stdev X - (original variable name: tBodyAccJerk-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.991271925,	-0.95130285,	-0.63978102073413,	-0.29120268,	1

time_body_acc_jerk_stdev_y
:	Time Body Acc Jerk Stdev Y - (original variable name: tBodyAccJerk-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.985006875,	-0.92504404,	-0.607971599340832,	-0.221772985,	1

time_body_acc_jerk_stdev_z
:	Time Body Acc Jerk Stdev Z - (original variable name: tBodyAccJerk-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.989195665,	-0.95427861,	-0.762820240449202,	-0.54848816,	1

time_body_gyro_mean_x
:	Time Body Gyro Mean X - (original variable name: tBodyGyro-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.045787107,	-0.027762646,	-0.0309824871713436,	-0.010576503,	1

time_body_gyro_mean_y
:	Time Body Gyro Mean Y - (original variable name: tBodyGyro-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.10399034,	-0.074767602,	-0.0747194855994359,	-0.0510963965,	1

time_body_gyro_mean_z
:	Time Body Gyro Mean Z - (original variable name: tBodyGyro-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	0.0648460705,	0.086261317,	0.088357304227173,	0.11043857,	1

time_body_gyro_stdev_x
:	Time Body Gyro Stdev X - (original variable name: tBodyGyro-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.987190665,	-0.90159356,	-0.721192598029789,	-0.48222822,	1

time_body_gyro_stdev_y
:	Time Body Gyro Stdev Y - (original variable name: tBodyGyro-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98189823,	-0.9105644,	-0.682653506899942,	-0.44608838,	1

time_body_gyro_stdev_z
:	Time Body Gyro Stdev Z - (original variable name: tBodyGyro-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.985008215,	-0.88192059,	-0.653665674372188,	-0.33789777,	1

time_body_gyro_jerk_mean_x
:	Time Body Gyro Jerk Mean X - (original variable name: tBodyGyroJerk-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.117232615,	-0.09824338,	-0.0967092754729682,	-0.079304,	1

time_body_gyro_jerk_mean_y
:	Time Body Gyro Jerk Mean Y - (original variable name: tBodyGyroJerk-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.0586814845,	-0.040556805,	-0.0423181079782632,	-0.025210938,	1

time_body_gyro_jerk_mean_z
:	Time Body Gyro Jerk Mean Z - (original variable name: tBodyGyroJerk-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.0793580545,	-0.054554317,	-0.0548303497968374,	-0.0316826445,	1

time_body_gyro_jerk_stdev_x
:	Time Body Gyro Jerk Stdev X - (original variable name: tBodyGyroJerk-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.99072564,	-0.93480864,	-0.731348533131935,	-0.48653805,	1

time_body_gyro_jerk_stdev_y
:	Time Body Gyro Jerk Stdev Y - (original variable name: tBodyGyroJerk-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.992234135,	-0.95478851,	-0.786062320321895,	-0.62679006,	1

time_body_gyro_jerk_stdev_z
:	Time Body Gyro Jerk Stdev Z - (original variable name: tBodyGyroJerk-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.992567455,	-0.95031422,	-0.739932395222129,	-0.50971305,	1

time_body_acc_mag_mean
:	Time Body Acc Mag Mean - (original variable name: tBodyAccMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98191531,	-0.87463491,	-0.54822165976717,	-0.12014189,	1

time_body_acc_mag_stdev
:	Time Body Acc Mag Stdev - (original variable name: tBodyAccMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.982181585,	-0.84370796,	-0.591225327146546,	-0.242323295,	1

time_gravity_acc_mag_mean
:	Time Gravity Acc Mag Mean - (original variable name: tGravityAccMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98191531,	-0.87463491,	-0.54822165976717,	-0.12014189,	1

time_gravity_acc_mag_stdev
:	Time Gravity Acc Mag Stdev - (original variable name: tGravityAccMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.982181585,	-0.84370796,	-0.591225327146546,	-0.242323295,	1

time_body_acc_jerk_mag_mean
:	Time Body Acc Jerk Mag Mean - (original variable name: tBodyAccJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98955992,	-0.94809484,	-0.649417950650692,	-0.29558424,	1

time_body_acc_jerk_mag_stdev
:	Time Body Acc Jerk Mag Stdev - (original variable name: tBodyAccJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.990687475,	-0.92883947,	-0.627762945785391,	-0.27332015,	1

time_body_gyro_mag_mean
:	Time Body Gyro Mag Mean - (original variable name: tBodyGyroMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.978135745,	-0.82228682,	-0.60524856977632,	-0.24535442,	1

time_body_gyro_mag_stdev
:	Time Body Gyro Mag Stdev - (original variable name: tBodyGyroMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.9774915,	-0.82588331,	-0.662533062898382,	-0.39404253,	1

time_body_gyro_jerk_mag_mean
:	Time Body Gyro Jerk Mag Mean - (original variable name: tBodyGyroJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.992325655,	-0.95593685,	-0.762137610987416,	-0.549850065,	1

time_body_gyro_jerk_mag_stdev
:	Time Body Gyro Jerk Mag Stdev - (original variable name: tBodyGyroJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.992190985,	-0.94030231,	-0.77799317279698,	-0.609338455,	1

freq_body_acc_mean_x
:	Freq Body Acc Mean X - (original variable name: fBodyAcc-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.991255955,	-0.94557918,	-0.622761658493734,	-0.264554765,	1

freq_body_acc_mean_y
:	Freq Body Acc Mean Y - (original variable name: fBodyAcc-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.979218375,	-0.86434494,	-0.53749328145871,	-0.103228395,	1

freq_body_acc_mean_z
:	Freq Body Acc Mean Z - (original variable name: fBodyAcc-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98322684,	-0.89535361,	-0.665033506271952,	-0.366240055,	1

freq_body_acc_stdev_x
:	Freq Body Acc Stdev X - (original variable name: fBodyAcc-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.992916635,	-0.94157527,	-0.603356276555826,	-0.249344685,	1

freq_body_acc_stdev_y
:	Freq Body Acc Stdev Y - (original variable name: fBodyAcc-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.976887385,	-0.83261287,	-0.528420009576204,	-0.092156306,	1

freq_body_acc_stdev_z
:	Freq Body Acc Stdev Z - (original variable name: fBodyAcc-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.97797651,	-0.83978721,	-0.617874813333395,	-0.302252065,	1

freq_body_acc_mean_freq_x
:	Freq Body Acc Mean Freq X - (original variable name: fBodyAcc-meanFreq()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.41878138,	-0.23825143,	-0.2214691368263,	-0.0204315155,	1

freq_body_acc_mean_freq_y
:	Freq Body Acc Mean Freq Y - (original variable name: fBodyAcc-meanFreq()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.14477196,	0.0046658081,	0.015400588735675,	0.176602965,	1

freq_body_acc_mean_freq_z
:	Freq Body Acc Mean Freq Z - (original variable name: fBodyAcc-meanFreq()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.13844984,	0.060842915,	0.0473098698476722,	0.24922413,	1

freq_body_acc_jerk_mean_x
:	Freq Body Acc Jerk Mean X - (original variable name: fBodyAccJerk-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.99124468,	-0.95159528,	-0.656713524546605,	-0.32698327,	1

freq_body_acc_jerk_mean_y
:	Freq Body Acc Jerk Mean Y - (original variable name: fBodyAccJerk-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.984776155,	-0.92570213,	-0.628961179980356,	-0.263846875,	1

freq_body_acc_jerk_mean_z
:	Freq Body Acc Jerk Mean Z - (original variable name: fBodyAccJerk-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98728199,	-0.94753336,	-0.743608246170053,	-0.51332898,	1

freq_body_acc_jerk_stdev_x
:	Freq Body Acc Jerk Stdev X - (original variable name: fBodyAccJerk-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.99202975,	-0.95624097,	-0.654979816705833,	-0.32030207,	1

freq_body_acc_jerk_stdev_y
:	Freq Body Acc Jerk Stdev Y - (original variable name: fBodyAccJerk-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.986467325,	-0.92803444,	-0.612243590244114,	-0.236096955,	1

freq_body_acc_jerk_stdev_z
:	Freq Body Acc Jerk Stdev Z - (original variable name: fBodyAccJerk-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.989532085,	-0.9589843,	-0.780928428167213,	-0.59028609,	1

freq_body_acc_jerk_mean_freq_x
:	Freq Body Acc Jerk Mean Freq X - (original variable name: fBodyAccJerk-meanFreq()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.29769711,	-0.045441261,	-0.0477062917542325,	0.204465715,	1

freq_body_acc_jerk_mean_freq_y
:	Freq Body Acc Jerk Mean Freq Y - (original variable name: fBodyAccJerk-meanFreq()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.427950895,	-0.23653033,	-0.213392904926883,	0.0086511494,	1

freq_body_acc_jerk_mean_freq_z
:	Freq Body Acc Jerk Mean Freq Z - (original variable name: fBodyAccJerk-meanFreq()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.33139146,	-0.10245805,	-0.123828014584147,	0.091239681,	1

freq_body_gyro_mean_x
:	Freq Body Gyro Mean X - (original variable name: fBodyGyro-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98531089,	-0.89168731,	-0.672094306818974,	-0.383672965,	1

freq_body_gyro_mean_y
:	Freq Body Gyro Mean Y - (original variable name: fBodyGyro-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.984723975,	-0.91969317,	-0.70621663959074,	-0.473482245,	1

freq_body_gyro_mean_z
:	Freq Body Gyro Mean Z - (original variable name: fBodyGyro-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.985133285,	-0.88771259,	-0.644192752866115,	-0.322457185,	1

freq_body_gyro_stdev_x
:	Freq Body Gyro Stdev X - (original variable name: fBodyGyro-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98809624,	-0.90532634,	-0.738594816501343,	-0.52245449,	1

freq_body_gyro_stdev_y
:	Freq Body Gyro Stdev Y - (original variable name: fBodyGyro-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98084305,	-0.9061012,	-0.674226934551517,	-0.438502735,	1

freq_body_gyro_stdev_z
:	Freq Body Gyro Stdev Z - (original variable name: fBodyGyro-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.986176505,	-0.89150579,	-0.690446312501126,	-0.41676661,	1

freq_body_gyro_mean_freq_x
:	Freq Body Gyro Mean Freq X - (original variable name: fBodyGyro-meanFreq()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.27189311,	-0.098680774,	-0.101042702224631,	0.068104999,	1

freq_body_gyro_mean_freq_y
:	Freq Body Gyro Mean Freq Y - (original variable name: fBodyGyro-meanFreq()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.362570275,	-0.17297859,	-0.174277577553958,	0.013663873,	1

freq_body_gyro_mean_freq_z
:	Freq Body Gyro Mean Freq Z - (original variable name: fBodyGyro-meanFreq()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.23240119,	-0.053693106,	-0.0513928953203266,	0.122512095,	1

freq_body_acc_mag_mean
:	Freq Body Acc Mag Mean - (original variable name: fBodyAccMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.984737435,	-0.8755028,	-0.585962696268539,	-0.21731156,	1

freq_body_acc_mag_stdev
:	Freq Body Acc Mag Stdev - (original variable name: fBodyAccMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.98288442,	-0.85472798,	-0.659531216655476,	-0.38232853,	1

freq_body_acc_mag_mean_freq
:	Freq Body Acc Mag Mean Freq - (original variable name: fBodyAccMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.0966299635,	0.0702558,	0.0768760112631957,	0.24495376,	1

freq_body_body_acc_jerk_mag_mean
:	Freq Body Body Acc Jerk Mag Mean - (original variable name: fBodyBodyAccJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.989783585,	-0.92898699,	-0.620789916331592,	-0.25997022,	1

freq_body_body_acc_jerk_mag_stdev
:	Freq Body Body Acc Jerk Mag Stdev - (original variable name: fBodyBodyAccJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.990664305,	-0.92553151,	-0.640076803144351,	-0.308152375,	1

freq_body_body_acc_jerk_mag_mean_freq
:	Freq Body Body Acc Jerk Mag Mean Freq - (original variable name: fBodyBodyAccJerkMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.0029593156,	0.16417982,	0.173219742700723,	0.357306605,	1

freq_body_body_gyro_mag_mean
:	Freq Body Body Gyro Mag Mean - (original variable name: fBodyBodyGyroMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.982501535,	-0.87562004,	-0.697411069729937,	-0.451399795,	1

freq_body_body_gyro_mag_stdev
:	Freq Body Body Gyro Mag Stdev - (original variable name: fBodyBodyGyroMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.97815001,	-0.82748975,	-0.699976372277643,	-0.471266725,	1

freq_body_body_gyro_mag_mean_freq
:	Freq Body Body Gyro Mag Mean Freq - (original variable name: fBodyBodyGyroMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.23435586,	-0.052095469,	-0.0415636227771787,	0.151575465,	1

freq_body_body_gyro_jerk_mag_mean
:	Freq Body Body Gyro Jerk Mag Mean - (original variable name: fBodyBodyGyroJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.9921084,	-0.94534436,	-0.779767633083527,	-0.61224246,	1

freq_body_body_gyro_jerk_mag_stdev
:	Freq Body Body Gyro Jerk Mag Stdev - (original variable name: fBodyBodyGyroJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.992574895,	-0.93821243,	-0.792190209274884,	-0.64373796,	1

freq_body_body_gyro_jerk_mag_mean_freq
:	Freq Body Body Gyro Jerk Mag Mean Freq - (original variable name: fBodyBodyGyroJerkMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-1,	-0.019480753,	0.1362451,	0.126707820497791,	0.288959895,	1

	
## Means By Subject then Activity Data Codes

subject
:	Subject
:		ID from 1 - 30

activity
:	Activity
:	  1 of 6 different Activities each row representing the mean for that variables subject activity combination:
:    LAYING            SITTING           STANDING            WALKING WALKING_DOWNSTAIRS   WALKING_UPSTAIRS 

time_body_acc_mean_x
:	Time Body Acc Mean X - (original variable name: tBodyAcc-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		0.22159824394,	0.271213278524359,	0.276964936014357,	0.274302742245795,	0.28000456109745,	0.3014610196

time_body_acc_mean_y
:	Time Body Acc Mean Y - (original variable name: tBodyAcc-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.0405139534294,	-0.0200219798748889,	-0.0172620496866845,	-0.0178755238674415,	-0.0149358017110554,	-0.00130828765170213

time_body_acc_mean_z
:	Time Body Acc Mean Z - (original variable name: tBodyAcc-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.152513899520833,	-0.112074450244479,	-0.10819133976087,	-0.109163815804519,	-0.104428752980891,	-0.07537846886

time_body_acc_stdev_x
:	Time Body Acc Stdev X - (original variable name: tBodyAcc-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.996068635384615,	-0.979867974370629,	-0.752561958811551,	-0.557690076404401,	-0.198377215776941,	0.626917070512821

time_body_acc_stdev_y
:	Time Body Acc Stdev Y - (original variable name: tBodyAcc-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.990240946666667,	-0.942050819376984,	-0.508965351555332,	-0.460462635378301,	-0.0307676595294766,	0.616937015333333

time_body_acc_stdev_z
:	Time Body Acc Stdev Z - (original variable name: tBodyAcc-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.987658662307692,	-0.949807491997863,	-0.651757405423516,	-0.575560246148636,	-0.230639460845138,	0.609017879074074

time_gravity_acc_mean_x
:	Time Gravity Acc Mean X - (original variable name: tGravityAcc-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.680043155060241,	0.837592916043128,	0.920838883913399,	0.697477505882702,	0.942516857688787,	0.974508732

time_gravity_acc_mean_y
:	Time Gravity Acc Mean Y - (original variable name: tGravityAcc-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.479894842941176,	-0.233187799109687,	-0.127822394803259,	-0.0162128361521394,	0.0877306139342137,	0.956593814210526

time_gravity_acc_mean_z
:	Time Gravity Acc Mean Z - (original variable name: tGravityAcc-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.49508872037037,	-0.117261404755941,	0.0238412209314665,	0.0741278709325255,	0.149455890473864,	0.9578730416

time_gravity_acc_stdev_x
:	Time Gravity Acc Stdev X - (original variable name: tGravityAcc-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.996764227384615,	-0.982451702372549,	-0.969465682760801,	-0.96375253077172,	-0.950856547082621,	-0.829554947808219

time_gravity_acc_stdev_y
:	Time Gravity Acc Stdev Y - (original variable name: tGravityAcc-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.99424764884058,	-0.971146645627721,	-0.959033035282651,	-0.952429559765945,	-0.937014950155746,	-0.643578361424658

time_gravity_acc_stdev_z
:	Time Gravity Acc Stdev Z - (original variable name: tGravityAcc-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.990957249538462,	-0.960509391633387,	-0.945002365380835,	-0.93640104156585,	-0.917985372777778,	-0.610161166287671

time_body_acc_jerk_mean_x
:	Time Body Acc Jerk Mean X - (original variable name: tBodyAccJerk-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		0.0426880986186441,	0.0739568738000597,	0.0763999692824201,	0.0794735599203562,	0.083295352047549,	0.130193043809524

time_body_acc_jerk_mean_y
:	Time Body Acc Jerk Mean Y - (original variable name: tBodyAccJerk-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.0386872111282051,	0.000466401851062504,	0.0094697935989457,	0.00756520996888408,	0.0134008349196413,	0.056818586275

time_body_acc_jerk_mean_z
:	Time Body Acc Jerk Mean Z - (original variable name: tBodyAccJerk-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.0674583919268293,	-0.0106010614839614,	-0.0038606227443805,	-0.00495340328183431,	0.00195821302563266,	0.0380533591627451

time_body_acc_jerk_stdev_x
:	Time Body Acc Jerk Stdev X - (original variable name: tBodyAccJerk-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994604542264151,	-0.983183434756787,	-0.810364617825977,	-0.594946699510964,	-0.223280808953904,	0.544273037307692

time_body_acc_jerk_stdev_y
:	Time Body Acc Jerk Stdev Y - (original variable name: tBodyAccJerk-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.989513565652174,	-0.972398671721195,	-0.775640254646154,	-0.565414714340423,	-0.148331403853806,	0.355306716915385

time_body_acc_jerk_stdev_z
:	Time Body Acc Jerk Stdev Z - (original variable name: tBodyAccJerk-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.993288313333333,	-0.982661424585289,	-0.883656741553846,	-0.735957689241115,	-0.512123354962264,	0.0310157077775926

time_body_gyro_mean_x
:	Time Body Gyro Mean X - (original variable name: tBodyGyro-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.205775427307692,	-0.0471158802354843,	-0.0287050671386677,	-0.0324371599031218,	-0.016760840078875,	0.19270447595122

time_body_gyro_mean_y
:	Time Body Gyro Mean Y - (original variable name: tBodyGyro-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.204205356087805,	-0.0895496283737727,	-0.073182294529017,	-0.0742595723452297,	-0.0611346308215,	0.0274707556666667

time_body_gyro_mean_z
:	Time Body Gyro Mean Z - (original variable name: tBodyGyro-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.0724546025804878,	0.0747495349861111,	0.0851214588562313,	0.0874446468695526,	0.101769148181955,	0.179102058245614

time_body_gyro_stdev_x
:	Time Body Gyro Stdev X - (original variable name: tBodyGyro-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994276591304348,	-0.97346578628022,	-0.78899182266,	-0.691639902777431,	-0.441424727989583,	0.267657219333333

time_body_gyro_stdev_y
:	Time Body Gyro Stdev Y - (original variable name: tBodyGyro-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994210471914894,	-0.962932891415663,	-0.801683738898021,	-0.653302029911363,	-0.419583542056738,	0.476518714444444

time_body_gyro_stdev_z
:	Time Body Gyro Stdev Z - (original variable name: tBodyGyro-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.985538363333333,	-0.960949536367123,	-0.8010010881621,	-0.616435294332593,	-0.3106139752125,	0.564875818162963

time_body_gyro_jerk_mean_x
:	Time Body Gyro Jerk Mean X - (original variable name: tBodyGyroJerk-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.157212539189362,	-0.103222980830721,	-0.0986833593296509,	-0.0960567959204382,	-0.091104489353952,	-0.0220916265065217

time_body_gyro_jerk_mean_y
:	Time Body Gyro Jerk Mean Y - (original variable name: tBodyGyroJerk-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.0768089915604167,	-0.0455161807548247,	-0.0411175370152025,	-0.0426927819752453,	-0.0384237828250595,	-0.0132022768074468

time_body_gyro_jerk_mean_z
:	Time Body Gyro Jerk Mean Z - (original variable name: tBodyGyroJerk-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.0924998531372549,	-0.061724502170303,	-0.0534296148538262,	-0.0548018825799509,	-0.0489849630433245,	-0.00694066389361702

time_body_gyro_jerk_stdev_x
:	Time Body Gyro Jerk Stdev X - (original variable name: tBodyGyroJerk-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.99654254057971,	-0.979981451666667,	-0.839648774710345,	-0.703632714557601,	-0.462888852229951,	0.179148649684615

time_body_gyro_jerk_stdev_y
:	Time Body Gyro Jerk Stdev Y - (original variable name: tBodyGyroJerk-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.997081575652174,	-0.983213512094418,	-0.89417791168862,	-0.763551835158898,	-0.586105529305806,	0.295945926186441

time_body_gyro_jerk_stdev_z
:	Time Body Gyro Jerk Stdev Z - (original variable name: tBodyGyroJerk-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.995380794637681,	-0.984785148098555,	-0.860964365777116,	-0.709559184010004,	-0.474055587375801,	0.193206498960417

time_body_acc_mag_mean
:	Time Body Acc Mag Mean - (original variable name: tBodyAccMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.986493196666667,	-0.957281005657021,	-0.482883603047945,	-0.49728966685894,	-0.0919023342314332,	0.644604325128205

time_body_acc_mag_stdev
:	Time Body Acc Mag Stdev - (original variable name: tBodyAccMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.986464542615385,	-0.943004626938844,	-0.607428117013143,	-0.543908670845839,	-0.208986277252094,	0.428405922622222

time_gravity_acc_mag_mean
:	Time Gravity Acc Mag Mean - (original variable name: tGravityAccMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.986493196666667,	-0.957281005657021,	-0.482883603047945,	-0.49728966685894,	-0.0919023342314332,	0.644604325128205

time_gravity_acc_mag_stdev
:	Time Gravity Acc Mag Stdev - (original variable name: tGravityAccMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.986464542615385,	-0.943004626938844,	-0.607428117013143,	-0.543908670845839,	-0.208986277252094,	0.428405922622222

time_body_acc_jerk_mag_mean
:	Time Body Acc Jerk Mag Mean - (original variable name: tBodyAccJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.99281471515625,	-0.98074058947065,	-0.816778554069231,	-0.607929591545179,	-0.245610527039944,	0.434490400974359

time_body_acc_jerk_mag_stdev
:	Time Body Acc Jerk Mag Stdev - (original variable name: tBodyAccJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994646916811594,	-0.976547463993665,	-0.801379344123077,	-0.584175609709768,	-0.217256776430382,	0.450612065720513

time_body_gyro_mag_mean
:	Time Body Gyro Mag Mean - (original variable name: tBodyGyroMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.980740846769231,	-0.946130660996377,	-0.655079846599804,	-0.565163077212988,	-0.215885549512518,	0.418004608615385

time_body_gyro_mag_stdev
:	Time Body Gyro Mag Stdev - (original variable name: tBodyGyroMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.981372675614035,	-0.94763315575,	-0.742044287036863,	-0.630394720315622,	-0.360212253090837,	0.299975979851852

time_body_gyro_jerk_mag_mean
:	Time Body Gyro Jerk Mag Mean - (original variable name: tBodyGyroJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.997322526811594,	-0.985154617839873,	-0.864794595203118,	-0.736369300428253,	-0.511862618137223,	0.0875816618205128

time_body_gyro_jerk_mag_stdev
:	Time Body Gyro Jerk Mag Stdev - (original variable name: tBodyGyroJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.997666071594203,	-0.980453958536942,	-0.880926958143599,	-0.755015188509002,	-0.576738785909962,	0.250173204117966

freq_body_acc_mean_x
:	Freq Body Acc Mean X - (original variable name: fBodyAcc-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.995249932641509,	-0.97868853411456,	-0.769093140075898,	-0.575799983503946,	-0.217441796672488,	0.537012022051282

freq_body_acc_mean_y
:	Freq Body Acc Mean Y - (original variable name: fBodyAcc-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.989034304057971,	-0.953614315417457,	-0.594984308629578,	-0.488732713013952,	-0.0634105967630682,	0.524187686888889

freq_body_acc_mean_z
:	Freq Body Acc Mean Z - (original variable name: fBodyAcc-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.989473926666667,	-0.961946941851852,	-0.723601712197489,	-0.62973875362598,	-0.318344106742647,	0.280735952206667

freq_body_acc_stdev_x
:	Freq Body Acc Stdev X - (original variable name: fBodyAcc-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.996604570307692,	-0.981991748844445,	-0.74699883447612,	-0.552201112392524,	-0.196639235920597,	0.658506543333333

freq_body_acc_stdev_y
:	Freq Body Acc Stdev Y - (original variable name: fBodyAcc-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.990680395362319,	-0.9404151031875,	-0.513377467163041,	-0.481478729871355,	-0.0791254311765882,	0.560191344

freq_body_acc_stdev_z
:	Freq Body Acc Stdev Z - (original variable name: fBodyAcc-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.987224804307692,	-0.945940057701613,	-0.644149346839498,	-0.582361415029381,	-0.265471193773626,	0.687124163703704

freq_body_acc_mean_freq_x
:	Freq Body Acc Mean Freq X - (original variable name: fBodyAcc-meanFreq()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.635913046346154,	-0.391654690833333,	-0.25730733733,	-0.23226609715376,	-0.0610456020163312,	0.159123629063636

freq_body_acc_mean_freq_y
:	Freq Body Acc Mean Freq Y - (original variable name: fBodyAcc-meanFreq()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.379518455061538,	-0.0813141053032487,	0.00785476566367266,	0.0115288797872382,	0.086280915594425,	0.466528231788462

freq_body_acc_mean_freq_z
:	Freq Body Acc Mean Freq Z - (original variable name: fBodyAcc-meanFreq()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.520114793584906,	-0.0362924978206101,	0.065823500655572,	0.0437174260645842,	0.175420218891,	0.402532553395833

freq_body_acc_jerk_mean_x
:	Freq Body Acc Jerk Mean X - (original variable name: fBodyAccJerk-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994630797358491,	-0.982838055851244,	-0.812641020130769,	-0.613928222283428,	-0.281953962751441,	0.474317256051282

freq_body_acc_jerk_mean_y
:	Freq Body Acc Jerk Mean Y - (original variable name: fBodyAccJerk-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.989398823913043,	-0.972537349877859,	-0.781656017361538,	-0.588163069360073,	-0.196305281263904,	0.276716853307692

freq_body_acc_jerk_mean_z
:	Freq Body Acc Jerk Mean Z - (original variable name: fBodyAccJerk-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.992018447826087,	-0.979617421167154,	-0.870663937715385,	-0.714358487490646,	-0.469689974390653,	0.157775692377778

freq_body_acc_jerk_stdev_x
:	Freq Body Acc Jerk Stdev X - (original variable name: fBodyAccJerk-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.995073759245283,	-0.9847182334014,	-0.825392273824716,	-0.612103283207987,	-0.247532895131528,	0.476803887476923

freq_body_acc_jerk_stdev_y
:	Freq Body Acc Jerk Stdev Y - (original variable name: fBodyAccJerk-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.990468082753623,	-0.973698764234543,	-0.785151940276923,	-0.570730968650136,	-0.168539754251887,	0.349771285415897

freq_body_acc_jerk_stdev_z
:	Freq Body Acc Jerk Stdev Z - (original variable name: fBodyAccJerk-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.993107759855072,	-0.983747468226374,	-0.895120677107692,	-0.756489426411787,	-0.543787024197993,	-0.00623647528983051

freq_body_acc_jerk_mean_freq_x
:	Freq Body Acc Jerk Mean Freq X - (original variable name: fBodyAccJerk-meanFreq()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.576044001875,	-0.289664811768519,	-0.0609122254010664,	-0.0691017912141093,	0.176596782275,	0.331449281481482

freq_body_acc_jerk_mean_freq_y
:	Freq Body Acc Jerk Mean Freq Y - (original variable name: fBodyAccJerk-meanFreq()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.601971415384615,	-0.397507304259764,	-0.232093202639008,	-0.228102065671109,	-0.0472055655846913,	0.195677336307692

freq_body_acc_jerk_mean_freq_z
:	Freq Body Acc Jerk Mean Freq Z - (original variable name: fBodyAccJerk-meanFreq()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.62755547372549,	-0.308670629374599,	-0.0918702088312327,	-0.137602308791712,	0.0385767655953241,	0.230107945944444

freq_body_gyro_mean_x
:	Freq Body Gyro Mean X - (original variable name: fBodyGyro-mean()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.99312260884058,	-0.969736398042929,	-0.729961304525143,	-0.636739605053057,	-0.338678948599554,	0.474962448333333

freq_body_gyro_mean_y
:	Freq Body Gyro Mean Y - (original variable name: fBodyGyro-mean()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994025488297872,	-0.96996167080314,	-0.814097490770167,	-0.676686800745998,	-0.445800238776596,	0.328817010088889

freq_body_gyro_mean_z
:	Freq Body Gyro Mean Z - (original variable name: fBodyGyro-mean()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.985957788,	-0.962424442479839,	-0.790931357562831,	-0.604391244378742,	-0.263481414683682,	0.492414379822222

freq_body_gyro_stdev_x
:	Freq Body Gyro Stdev X - (original variable name: fBodyGyro-std()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994652185217391,	-0.975014778333333,	-0.808598920489286,	-0.711035658050846,	-0.481327430402778,	0.196613286661538

freq_body_gyro_stdev_y
:	Freq Body Gyro Stdev Y - (original variable name: fBodyGyro-std()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994353086595745,	-0.960171743958333,	-0.796377933461187,	-0.645433416234092,	-0.41542225786518,	0.646233637037037

freq_body_gyro_stdev_z
:	Freq Body Gyro Stdev Z - (original variable name: fBodyGyro-std()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.986725274871795,	-0.96425495495471,	-0.82240037145104,	-0.657746585870822,	-0.391624540460784,	0.522454216314815

freq_body_gyro_mean_freq_x
:	Freq Body Gyro Mean Freq X - (original variable name: fBodyGyro-meanFreq()-X)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.395770150677419,	-0.213362799384874,	-0.115526767588235,	-0.104551025495773,	0.00265539970556469,	0.249209411510602

freq_body_gyro_mean_freq_y
:	Freq Body Gyro Mean Freq Y - (original variable name: fBodyGyro-meanFreq()-Y)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.666814815306122,	-0.29433169607681,	-0.157944540045706,	-0.167407475856434,	-0.0426914749279661,	0.273141323315789

freq_body_gyro_mean_freq_z
:	Freq Body Gyro Mean Freq Z - (original variable name: fBodyGyro-meanFreq()-Z)
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.507490866734694,	-0.154814104842965,	-0.0508112844922094,	-0.0571809440547551,	0.0415150051028045,	0.3770740968

freq_body_acc_mag_mean
:	Freq Body Acc Mag Mean - (original variable name: fBodyAccMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.986800645362319,	-0.955958448359886,	-0.670270983362273,	-0.536516692548498,	-0.16221061166475,	0.586637550769231

freq_body_acc_mag_stdev
:	Freq Body Acc Mag Stdev - (original variable name: fBodyAccMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.987648484461539,	-0.945163322215909,	-0.651262934905251,	-0.620963293005196,	-0.365405566482713,	0.178684580868889

freq_body_acc_mag_mean_freq
:	Freq Body Acc Mag Mean Freq - (original variable name: fBodyAccMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.312338030213846,	-0.0147471340045142,	0.0813178394709229,	0.0761281754555899,	0.174361445730828,	0.435846931652174

freq_body_body_acc_jerk_mag_mean
:	Freq Body Body Acc Jerk Mag Mean - (original variable name: fBodyBodyAccJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.993998275797101,	-0.976971904809942,	-0.794047735707692,	-0.575617493234432,	-0.187234617002629,	0.538404846128205

freq_body_body_acc_jerk_mag_stdev
:	Freq Body Body Acc Jerk Mag Stdev - (original variable name: fBodyBodyAccJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.994366667681159,	-0.975196689475806,	-0.812618834107692,	-0.599160868317743,	-0.266817308808422,	0.316346415348718

freq_body_body_acc_jerk_mag_mean_freq
:	Freq Body Body Acc Jerk Mag Mean Freq - (original variable name: fBodyBodyAccJerkMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.125210388757581,	0.0452719304260474,	0.171982802993377,	0.162545885494571,	0.275927550202545,	0.488088499666667

freq_body_body_gyro_mag_mean
:	Freq Body Body Gyro Mag Mean - (original variable name: fBodyBodyGyroMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.986535242105263,	-0.961611471342593,	-0.765709363092157,	-0.667099099613148,	-0.408677139806763,	0.203979764835897

freq_body_body_gyro_mag_stdev
:	Freq Body Body Gyro Mag Stdev - (original variable name: fBodyBodyGyroMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.981468841692308,	-0.948779877895425,	-0.772728220624314,	-0.672322349574843,	-0.427694200155279,	0.236659662496296

freq_body_body_gyro_mag_mean_freq
:	Freq Body Body Gyro Mag Mean Freq - (original variable name: fBodyBodyGyroMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.456638670923077,	-0.169508727685073,	-0.0535216170714523,	-0.0360322479939937,	0.0822762372338021,	0.409521611525424

freq_body_body_gyro_jerk_mag_mean
:	Freq Body Body Gyro Jerk Mag Mean - (original variable name: fBodyBodyGyroJerkMag-mean())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.997617389275362,	-0.981301579017565,	-0.877896583992678,	-0.756385271117363,	-0.583114934960406,	0.146618569064407

freq_body_body_gyro_jerk_mag_stdev
:	Freq Body Body Gyro Jerk Mag Stdev - (original variable name: fBodyBodyGyroJerkMag-std())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.99758523057971,	-0.980155163191824,	-0.894068356326169,	-0.771517051737343,	-0.608065868486683,	0.287834616098305

freq_body_body_gyro_jerk_mag_mean_freq
:	Freq Body Body Gyro Jerk Mag Mean Freq - (original variable name: fBodyBodyGyroJerkMag-meanFreq())
:		Min.,	1st Qu.,	Median,	Mean,	3rd Qu.,	Max.
:		-0.182923596577778,	0.0542315706270573,	0.111560706294131,	0.125922459004982,	0.208051596971466,	0.426301679855072
